name: development-ci
run-name: ${{ github.actor }} CI development run

on:
  push:
    # Do not run when merging into develop or master
    branches-ignore:
      - 'develop'
      - 'main'

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # architecture: 'x64' # The default

      - name: Display the Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get fork point
        id: forkpoint
        # List all the commits in branch yet to be applied to develop (git
        # cherry), then take the first one (head) and pull the commit hash from
        # the line (awk), and request the commit hash before that one (git show
        # ... <hash>^1). This gives us the fork point hash. We need to check
        # out the develop branch before doing this, but use "fetch" so we do
        # not change to the develop branch.
        run: |
          git fetch origin develop:develop
          echo "fork=$(git show $(git cherry -v develop | head -n 1 | awk '{ print $2 }')^1 --format=%H | head -n 1)" >> $GITHUB_ENV

      - name: Get changed files
        id: changes
        # Adds all changed files as env.all, and changed python files as env.python
        run: |
          echo "Fork point hash: ${{ env.fork }}"

          echo -e "\n"
          echo "All changed files:"
          git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} || echo '<none>'
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} | xargs)" >> $GITHUB_ENV

          echo -e "\n"
          echo "Changed python files:"
          git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} | grep .py$ || echo '<none>'
          echo "python=$(git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} | grep .py$ | xargs)" >> $GITHUB_ENV

      # Run Black on the whole repo
      - name: Run Black to check the code for formatting problems
        if: ${{ env.python }}
        # If any code needs reformatting, black returns an exit code of 1,
        # which fails the action
        run: black --check ${{ env.python }}

      # Run flake8 on the vane and tests directories
      - name: Lint with flake8
        if: ${{ env.python }}
        run: flake8 ${{ env.python }}

      # Run pylint on the vane and tests directories
      - name: Lint with pylint
        if: ${{ env.python }}
        run: pylint ${{ env.python }}
